config/routes.rb
scope '/projects/:project_id' do
  resources :test_suites
  resources :test_cases do
    member do
      post :delete_test_case_step
      get :move
    end
  end
  resources :test_suite_test_cases
  resources :test_plans do
    member do
      get :add_test_case
    end
  end
  resources :test_executions
  resources :test_execution_issues
end

get '/projects/:project_id/test', :to => 'testmine#index', as: 'testmine_index'
get '/projects/:project_id/test/test_execution/:test_execution_id', :to => 'testmine#test_execution', as: 'testmine_test_execution'
get '/projects/:project_id/test/test_plan/:test_plan_id', :to => 'testmine#test_plan', as: 'testmine_test_plan'
get '/projects/:project_id/test/edit_test_plan/:test_plan_id', :to => 'testmine#edit_test_plan', as: 'testmine_edit_test_plan'

# get '/projects/:project_id/test_suites', :to => 'test_suites#index', as: 'test_suites'
# get '/projects/:project_id/test_suites/new', :to => 'test_suites#new', as: 'new_test_suite'
# post '/projects/:project_id/test_suites', :to => 'test_suites#create', as: 'test_suites'

# get '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#index', as: 'test_cases'
# get '/projects/:project_id/test_suites/:test_suite_id/test_cases/new', :to => 'test_cases#new', as: 'new_test_case'
# post '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#create', as: 'test_cases'

app/models/test_execution.rb
class TestExecution < ActiveRecord::Base
  unloadable

  belongs_to :test_case
  belongs_to :test_plan
  belongs_to :test_execution_status
  belongs_to :executed_by, class_name: 'User', foreign_key: :executed_by_user_id

  has_many :test_execution_issues
  has_many :issues, through: :test_execution_issues

  accepts_nested_attributes_for :test_case

  before_save :check_test_plan_status

  def check_test_plan_status
    if self.test_plan
      return self.test_plan.executable?
    end
  end

  def executed?
    !self.test_execution_status.nil?
  end
end

app/controllers/test_executions_controller.rb
class TestExecutionsController < ApplicationController
  unloadable

  before_filter :find_project
  before_filter :authorize

  after_filter :set_executed_by, on: [ :update ]

  def create
    @test_execution = TestExecution.new
    @test_execution.test_plan_id = params[:test_execution][:test_plan_id]
    @test_execution.test_case_id = params[:test_execution][:test_case_id]
    @test_case = TestCase.find(params[:test_execution][:test_case_id])
    @test_plan ||= TestPlan.find(params[:test_execution][:test_plan_id])

    if @test_execution.test_plan.finished?
      render 'create_failed.js'
    else
      if @test_execution.save
        render 'create.js'
      end
    end
  end

  def update
    @test_execution = TestExecution.find(params[:id])

    if @test_execution.update_attributes(params[:test_execution])
      render 'update.js'
    end
  end

  private
  def find_project
    identifier = params[:project_id]

    @project = Project.find(identifier)
  end

  def set_executed_by
    if @test_execution && @test_execution.test_plan
      @test_execution.executed_by = User.current if @test_execution.test_plan.finished?
      @test_execution.save
    end
  end
end

app/views/test_executions/_form.html.erb
<%
  options = { remote: true }
  if test_execution.persisted?
    options[:url] = test_execution_path(@project, test_execution)
  else
    options[:url] = test_executions_path(@project)
  end
%>
<%= labelled_form_for test_execution, options do |f| %>
  <%= f.fields_for :test_case do |p| %>
    <p class="full-label">
      <%= p.text_field :title, label: 'Title' %>
    </p>
    <p class="full-label">
      <%= p.text_area :summary, label: 'Summary', rows: 3 %>
    </p>
    <p class="full-label">
      <%= p.text_area :preconditions, label: 'Preconditions', rows: 2 %>
    </p>
    <div class="two-columns">
      <div class="column">
        <p>
          <%= p.select :test_case_status_id, options_from_collection_for_select(TestCaseStatus.all, :id, :name), label: 'Status' %>
        </p>
        <p>
          <%= p.select :test_case_execution_type_id, options_from_collection_for_select(TestCaseExecutionType.all, :id, :name), label: 'Type' %>
        </p>
      </div>
      <div class="column">
        <p>
          <%= p.select :test_case_importance_id, options_from_collection_for_select(TestCaseImportance.all, :id, :name), label: 'Importance' %>
        </p>
        <p>
          <%= p.number_field :duration, label: 'Time Exec. (min)' %>
        </p>
      </div>
    </div>
    <div id="test_case_steps">
      <label id="test_case_step_item">#</label>
      <label id="test_case_step_action">Steps Actions</label>
      <label id="test_case_step_expected_result">Expected Result</label>
      <%= p.fields_for :test_case_steps do |step_fields| %>
        <div class="test_case_step" <%= step_fields.object.persisted? ? "id=\"test_case_step_#{step_fields.object.id}\"".html_safe : "" %>>
          <%= step_fields.number_field :item, label: '', class: 'test_case_step_item' %>
          <%= step_fields.text_field :action, label: '', class: 'test_case_step_action' %>
          <%= step_fields.text_field :expected_result, label: '', class: 'test_case_step_expected_result' %>
        </div>
      <% end %>
    </div>
    <div class="two-columns">
      <div class="column">
        <%= f.text_area :comment, label: 'Comment', rows: 6 %>
      </div>
      <div class="column">
        <ul id="test_execution_status">
          <% TestExecutionStatus.all.each do |execution_status| %>
            <li>
              <%= f.radio_button :test_execution_status_id, execution_status.id %>
              <label for="test_execution_status_id_<%= execution_status.id %>"><%= execution_status.name %></label>
            </li>
          <% end %>
        </ul>
        <input type="button" id="new_issue" value="Bug" <%= !test_execution.persisted? ? 'disabled="disabled"'.html_safe : '' %> data-id="<%= test_execution.try(:id) %>" />
        <% if test_execution.test_plan %>
          <%= f.submit 'Execute', disabled: test_execution.test_plan.finished? %>
        <% else %>
          <%= f.submit 'Execute', disabled: true %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/test_executions/create.js.erb
var testPlan = $('#test_plan_<%= @test_execution.test_plan_id %>');
var testPlanTestCases = testPlan.find('.test_plan_test_cases');
testPlanTestCases.append("<%= escape_javascript(render(partial: 'test_cases/show', locals: { test_case: @test_case, test_plan_id: @test_execution.test_plan_id })) %>");
testPlan.find('h4').find('span').html('<%= @test_plan.title %> <a href="#" class="show_menu">(<%= @test_plan.test_cases.count %>)</a>');

window.currentModal.close();

app/views/test_executions/create_failed.js.erb
alert("This test plan can't accept more test cases");
window.currentModal.close();

app/views/test_executions/update.js.erb
var xhr = $.get('<%= testmine_test_execution_path(@project, @test_execution) %>');

xhr.done(function(html) {
  $('#test_execution_form').find('form').replaceWith(html);
});