config/routes.rb
scope '/projects/:project_id' do
  resources :test_suites
  resources :test_cases do
    member do
      post :delete_test_case_step
      get :move
    end
  end
  resources :test_suite_test_cases
  resources :test_plans do
    member do
      get :add_test_case
    end
  end
  resources :test_executions
  resources :test_execution_issues
end

get '/projects/:project_id/test', :to => 'testmine#index', as: 'testmine_index'
get '/projects/:project_id/test/test_execution/:test_execution_id', :to => 'testmine#test_execution', as: 'testmine_test_execution'
get '/projects/:project_id/test/test_plan/:test_plan_id', :to => 'testmine#test_plan', as: 'testmine_test_plan'
get '/projects/:project_id/test/edit_test_plan/:test_plan_id', :to => 'testmine#edit_test_plan', as: 'testmine_edit_test_plan'

# get '/projects/:project_id/test_suites', :to => 'test_suites#index', as: 'test_suites'
# get '/projects/:project_id/test_suites/new', :to => 'test_suites#new', as: 'new_test_suite'
# post '/projects/:project_id/test_suites', :to => 'test_suites#create', as: 'test_suites'

# get '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#index', as: 'test_cases'
# get '/projects/:project_id/test_suites/:test_suite_id/test_cases/new', :to => 'test_cases#new', as: 'new_test_case'
# post '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#create', as: 'test_cases'

app/models/test_suite.rb
class TestSuite < ActiveRecord::Base
  unloadable

  attr_accessible :name, :summary, :project_id

  belongs_to :project
  has_many :test_suite_test_cases
  has_many :test_cases, through: :test_suite_test_cases
end

app/controllers/test_suites_controller.rb
class TestSuitesController < ApplicationController
  unloadable

  before_filter :find_project
  before_filter :authorize

  def index
    @test_suite = TestSuite.new(project_id: @project.id)
  end

  def show
    @title = "View Test Suite"
    @disabled_form = true
    edit
  end

  def new
    @test_suite = TestSuite.new(project_id: @project.id)

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :new, layout: use_layout
  end

  def edit
    @test_suite = TestSuite.find(params[:id])

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :edit, layout: use_layout
  end

  def create
    @test_suite = TestSuite.new
    @test_suite.name = params[:test_suite][:name]
    @test_suite.summary = params[:test_suite][:summary]
    @test_suite.project_id = @project.try(:id) || params[:test_suite][:project_id]

    if @test_suite.save
      render 'create.js'
    end
  end

  def update
    @test_suite = TestSuite.find(params[:id])
    @test_suite.name = params[:test_suite][:name]
    @test_suite.summary = params[:test_suite][:summary]

    if @test_suite.save
      render 'update.js'
    end
  end

  def destroy
    @test_suite = TestSuite.find(params[:id])

    if @test_suite.destroy
      TestSuiteTestCase.where(test_suite_id: @test_suite.id).destroy_all
      render 'destroy.js'
    end
  end

  private
  def find_project
    identifier = params[:project_id]
    identifier ||= params[:test_suite][:project_id] if params[:test_suite]

    @project = Project.find(identifier)
  end
end

app/views/test_suites/_form.html.erb
<h3>
  <% if @title.present? %>
    <%= @title %>
  <% else %>
    <% if @test_suite.persisted? %>
      Edit Test Suite
    <% else %>
      New Test Suite
    <% end %>
  <% end %>
</h3>
<%
  options = { remote: true }
  if @test_suite.persisted?
    options[:url] = test_suite_path(@project, @test_suite)
  else
    options[:url] = test_suites_path(@project)
  end
%>
<%= labelled_form_for @test_suite, options do |f| %>
  <p>
    <%= f.text_field :name, label: 'Name' %>
  </p>
  <p>
    <%= f.text_area :summary, label: 'Summary', rows: 5 %>
  </p>
  
  <%= f.hidden_field :project_id %>
  <%= submit_tag 'Save', disabled: @disabled_form %>
  <input type="reset" value="Cancelar" class="close-modal" />
<% end %>

app/views/test_suites/_index.html.erb
<a href="<%= new_test_suite_path(@project) %>" class="show-new-test-suite"><small>New test suite</small></a>

<ul id="project_test_suites">
  <%= render partial: 'test_suites/show', collection: @project.test_suites, as: :test_suite %>
</ul>

<script type="text/html" id="new-test-suite-modal-content">
  <%= render 'test_suites/form' %>
</script>

<script type="text/html" id="show-test-suite-modal-content">
</script>

<script type="text/html" id="edit-test-suite-modal-content">
</script>

<script type="text/html" id="new-test-case-modal-content">
</script>

<script type="text/html" id="show-test-case-modal-content">
</script>

<script type="text/html" id="move-test-case-modal-content">
</script>

<script type="text/html" id="edit-test-case-modal-content">
</script>

app/views/test_suites/_show.html.erb
<li id="test_suite_<%= test_suite.id %>">
  <h4 title="<%= test_suite.summary %>">
    <span>
      <%= test_suite.name %> <a href="#" class="show_menu">(<%= test_suite.test_cases.count %>)</a>
    </span>
    <ul class="menu">
      <li>
        <a href="<%= test_suite_path(@project, test_suite) %>" class="show-test-suite">
          View test suite
        </a>
      </li>
      <li>
        <a href="<%= edit_test_suite_path(@project, test_suite) %>" class="show-edit-test-suite">
          Edit test suite
        </a>
      </li>
      <li>
        <%= link_to "Delete test suite", test_suite_path(@project, test_suite), method: :delete, remote: true, confirm: "Are you sure you want to delete \"#{test_suite.name}\" Test Suite?" %>
      </li>
      <li style="border-top: solid 1px #999">
        <a href="<%= new_test_case_path(@project, test_suite_id: test_suite) %>" class="show-new-test-case">
          Create test case
        </a>
      </li>
    </ul>
  </h4>
  <ul class="test_suite_test_cases">
    <%= render partial: 'test_cases/show', collection: test_suite.test_cases, as: :test_case, locals: { test_suite_id: test_suite.id } %>
  </ul>
</li>

app/views/test_suites/create.js.erb
$("#project_test_suites").append("<%= escape_javascript(render(partial: 'test_suites/show', locals: { test_suite: @test_suite })) %>");

if (window.currentModal) {
  window.currentModal.close();
}

app/views/test_suites/destroy.js.erb
$('#test_suite_<%= @test_suite.id %>').remove();

app/views/test_suites/edit.html.erb
<%= render 'test_suites/form' %>

app/views/test_suites/index.html.erb
<h2>Test</h2>

<h3>
  <%= @project.name %> (<%= @project.test_cases.count %>)
  <a href="<%= new_test_suite_path(@project) %>" class="show-new-test-suite"><small>Create test suite</small></a>
</h3>
<ul id="project_test_suites">
<% @project.test_suites.each do |test_suite| %>
  <li id="test_suite_<%= test_suite.id %>">
    <h4>
      <%= test_suite.name %> (<%= test_suite.test_cases.count %>)
      <a href="<%= new_test_case_path(@project, test_suite) %>" class="show-new-test-case"><small>Create test case</small></a>
    </h4>
    <ul>
      <% test_suite.test_cases.each do |test_case| %>
        <li id="test_case_<%= test_case.id %>"><h5><%= test_case.title %></h5></li>
      <% end %>
    </ul>
  </li>
<% end %>
</ul>

<script type="text/html" id="new-test-case-modal-content">
</script>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'modal', :plugin => 'testmine' %>
  <%= javascript_include_tag 'modal', :plugin => 'testmine' %>
  <%= javascript_include_tag 'testmine', :plugin => 'testmine' %>
<% end %>

app/views/test_suites/new.html.erb
<%= render 'test_suites/form' %>

app/views/test_suites/show.html.erb
<%= render 'test_suites/form' %>

app/views/test_suites/update.js.erb
$('#test_suite_<%= @test_suite.id %>').find('h4 span').html('<%= @test_suite.name %> <a href="#" class="show_menu">(<%= @test_suite.test_cases.count %>)</a>');

if (window.currentModal) {
  window.currentModal.close();
}