config/routes.rb
scope '/projects/:project_id' do
  resources :test_suites
  resources :test_cases do
    member do
      post :delete_test_case_step
      get :move
    end
  end
  resources :test_suite_test_cases
  resources :test_plans do
    member do
      get :add_test_case
    end
  end
  resources :test_executions
  resources :test_execution_issues
end

get '/projects/:project_id/test', :to => 'testmine#index', as: 'testmine_index'
get '/projects/:project_id/test/test_execution/:test_execution_id', :to => 'testmine#test_execution', as: 'testmine_test_execution'
get '/projects/:project_id/test/test_plan/:test_plan_id', :to => 'testmine#test_plan', as: 'testmine_test_plan'
get '/projects/:project_id/test/edit_test_plan/:test_plan_id', :to => 'testmine#edit_test_plan', as: 'testmine_edit_test_plan'

# get '/projects/:project_id/test_suites', :to => 'test_suites#index', as: 'test_suites'
# get '/projects/:project_id/test_suites/new', :to => 'test_suites#new', as: 'new_test_suite'
# post '/projects/:project_id/test_suites', :to => 'test_suites#create', as: 'test_suites'

# get '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#index', as: 'test_cases'
# get '/projects/:project_id/test_suites/:test_suite_id/test_cases/new', :to => 'test_cases#new', as: 'new_test_case'
# post '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#create', as: 'test_cases'

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController
  unloadable

  before_filter :find_project
  before_filter :find_test_suite
  before_filter :authorize, except: [ :delete_test_case_step ]
  before_filter :clear_test_case_steps, only: [ :create, :update ]

  after_filter :append_to_test_suite, only: :create

  def index
  end

  def show
    @title = "View Test Case"
    @disabled_form = true
    edit
  end

  def new
    @test_case = TestCase.new(test_suite_id: params[:test_suite_id])

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :new, layout: use_layout
  end

  def edit
    @test_case = TestCase.find(params[:id])
    @test_case.test_suite_id = params[:test_suite_id]

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :edit, layout: use_layout
  end

  def create
    @test_case = TestCase.new(params[:test_case])
    @test_suite = TestSuite.find(@test_case.test_suite_id) if @test_case.test_suite_id.present?

    if @test_case.save
      render 'create.js'
    end
  end

  def update
    @test_case = TestCase.find(params[:id])
    @test_suite = TestSuite.find(@test_case.test_suite_id) if @test_case.test_suite_id.present?

    if @test_case.update_attributes(params[:test_case])
      render 'update.js'
    end
  end

  def destroy
    @test_case = TestCase.find(params[:id])
    @test_case.test_suite_id = params[:test_suite_id]

    if @test_case.destroy
      TestSuiteTestCase.where(test_case_id: @test_case.id).destroy_all
      render 'destroy.js'
    end
  end

  def move
    @test_suite_test_case = TestSuiteTestCase.where({
      test_case_id: params[:id],
      test_suite_id: params[:test_suite_id]
    }).first

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    respond_to do |format|
      format.html do
        render :move, layout: use_layout
      end

      format.json do
        render json: @test_suite_test_case
      end
    end
  end

  def delete_test_case_step
    @test_case_step = TestCaseStep.find(params[:test_case_step_id])
    if @test_case_step && @test_case_step.destroy
      render 'destroy_test_case_step.js'
    end
  end

  private
  def find_project
    identifier = params[:project_id]
    identifier ||= params[:test_case][:project_id] if params[:test_case]

    @project = Project.find(identifier)
  end

  def find_test_suite
    identifier = params[:test_suite_id]
    identifier ||= params[:test_case][:test_suite_id] if params[:test_case]

    @test_suite = TestSuite.find(identifier)
  end

  def append_to_test_suite
    if @test_suite.present?
      @test_suite.test_suite_test_cases << TestSuiteTestCase.new(test_suite_id: @test_suite.id, test_case_id: @test_case.id)
    end
  end

  def clear_test_case_steps
    params[:test_case][:test_case_steps_attributes].each do |i, attrs|
      if attrs[:action].blank? && attrs[:results].blank?
        params[:test_case][:test_case_steps_attributes].delete(i)
      end
    end
  end
end

app/views/test_cases/_form.html.erb
<h3>
  <% if @title.present? %>
    <%= @title %>
  <% else %>
    <% if @test_case.persisted? %>
      Edit Test Case
    <% else %>
      New Test Case
    <% end %>
  <% end %>
</h3>
<%
  options = { remote: true }
  if @test_case.persisted?
    options[:url] = test_case_path(@project, @test_case)
  else
    options[:url] = test_cases_path(@project)
  end
%>
<%= labelled_form_for @test_case, options do |f| %>
  <p>
    <%= f.text_field :title, label: 'Title' %>
  </p>
  <p>
    <%= f.text_area :summary, label: 'Summary', rows: 5 %>
  </p>
  <p>
    <%= f.text_area :preconditions, label: 'Pre Conditions', rows: 5 %>
  </p>
  <p>
    <%= f.select :document_id, options_from_collection_for_select(Document.all, :id, :title), label: 'Document' %>
  </p>
  <div class="two-columns">
    <div class="column">
      <p>
        <%= f.select :test_case_status_id, options_from_collection_for_select(TestCaseStatus.all, :id, :name), label: 'Status' %>
      </p>
      <p>
        <%= f.select :test_case_execution_type_id, options_from_collection_for_select(TestCaseExecutionType.all, :id, :name), label: 'Type' %>
      </p>
    </div>
    <div class="column">
      <p>
        <%= f.select :test_case_importance_id, options_from_collection_for_select(TestCaseImportance.all, :id, :name), label: 'Importance' %>
      </p>
      <p>
        <%= f.number_field :duration, label: 'Time Exec. (min)' %>
      </p>
    </div>
  </div>
  <div id="test_case_steps">
    <label id="test_case_step_item">#</label>
    <label id="test_case_step_action">Steps Actions</label>
    <label id="test_case_step_expected_result">Expected Result</label>
    <label id="add_test_case_step"><a href="#" class="add_test_case_step"><%= image_tag('add.png', plugin: 'testmine', width: 16) %></a></label>
    <%= f.fields_for :test_case_steps do |step_fields| %>
      <div class="test_case_step" <%= step_fields.object.persisted? ? "id=\"test_case_step_#{step_fields.object.id}\"".html_safe : "" %>>
        <%= step_fields.number_field :item, label: '', class: 'test_case_step_item' %>
        <%= step_fields.text_field :action, label: '', class: 'test_case_step_action' %>
        <%= step_fields.text_field :expected_result, label: '', class: 'test_case_step_expected_result' %>
        <a href="#" class="remove_test_case_step"><%= image_tag('remove.png', plugin: 'testmine', width: 16) %></a>
      </div>
    <% end %>
  </div>

  <%= f.hidden_field :test_suite_id %>
  <%= submit_tag 'Save', disabled: @disabled_form %>
  <input type="reset" value="Cancelar" class="close-modal" />
<% end %>

<script type="text/javascript">
  var testCaseStepsURLS = <%= @test_case.test_case_steps.inject({}) { |hash, test_case_step|
    if test_case_step.persisted?
      hash[test_case_step.id] = delete_test_case_step_test_case_path(@project.identifier, @test_case.id, test_case_step_id: test_case_step.id, test_suite_id: @test_case.test_suite_id)
    else
      hash[test_case_step.id] = '#'
    end
    
    hash
  }.to_json.html_safe %>;
</script>

app/views/test_cases/_show.html.erb
<%
  options = {}
  if defined? test_suite_id
    options[:test_suite_id] = test_suite_id
  end
  if defined? test_plan_id
    options[:test_plan_id] = test_plan_id
  end
%>
<li id="test_case_<%= test_case.id %>">
  <h5><%= test_case.title %></h5>
  <% if options[:test_suite_id].present? %>
    <ul class="menu">
      <li>
        <a href="<%= test_case_path(@project.identifier, test_case.id, options) %>" class="show-test-case">
          View test case
        </a>
      </li>
      <li>
        <a href="<%= edit_test_case_path(@project.identifier, test_case.id, options) %>" class="show-edit-test-case">
          Edit test case
        </a>
      </li>
      <li>
        <a href="<%= move_test_case_path(@project.identifier, test_case.id, options) %>" class="show-move-test-case">
          Move test case
        </a>
      </li>
      <li>
        <%= link_to "Delete test case", test_case_path(@project.identifier, test_case.id, options), method: :delete, remote: true, confirm: "Are you sure you want to delete \"#{test_case.title}\" Test Case?" %>
      </li>
    </ul>
  <% end %>
</li>

app/views/test_cases/create.js.erb
var testSuite = $("#test_suite_<%= @test_case.test_suite_id %>");
var testSuiteTestCases = testSuite.find('.test_suite_test_cases');
testSuiteTestCases.append("<%= escape_javascript(render(partial: 'test_cases/show', locals: { test_case: @test_case, test_suite_id: @test_case.test_suite_id })) %>");
testSuite.find('h4').find('span').html('<%= @test_suite.name %> <a href="#" class="show_menu">(<%= @test_suite.test_cases.count %>)</a>');

if (window.currentModal) {
  window.currentModal.close();
}

app/views/test_cases/destroy.js.erb
var testSuite = $("#test_suite_<%= @test_case.test_suite_id %>");
testSuite.find('ul').find('li#test_case_<%= @test_case.id %>').remove();

if (window.currentModal) {
  window.currentModal.close();
}

app/views/test_cases/destroy_test_case_step.js.erb
var testCaseStep = $('.test_case_step#test_case_step_<%= @test_case_step.id %>');
var testCaseStepHidden = testCaseStep.next('[type="hidden"]');

testCaseStep.remove();
testCaseStepHidden.remove();

app/views/test_cases/edit.html.erb
<%= render 'test_cases/form' %>

app/views/test_cases/move.html.erb
<h3>Move Test Case</h3>
<%= labelled_form_for @test_suite_test_case, url: test_suite_test_case_path(@project, @test_suite_test_case.id), remote: true do |f| %>
  <p>
    <%= f.select :test_suite_id, options_from_collection_for_select(TestSuite.all, :id, :name, @test_suite_test_case.test_suite_id), { label: 'Select Test Suite' }, { size: 3 } %>
  </p>
  <input type="hidden" name="previous_test_suite_id" value="<%= @test_suite_test_case.test_suite_id %>" />
  <%= f.submit 'Move' %>
  <input type="reset" value="Cancelar" class="close-modal" />
<% end %>

app/views/test_cases/new.html.erb
<%= render 'test_cases/form' %>

app/views/test_cases/update.js.erb
var testSuite = $("#test_suite_<%= @test_case.test_suite_id %>");
testSuite.find('ul').find('li#test_case_<%= @test_case.id %>').replaceWith("<%= escape_javascript(render(partial: 'test_cases/show', locals: { test_case: @test_case, test_suite_id: @test_case.test_suite_id })) %>");

if (window.currentModal) {
  window.currentModal.close();
}