config/routes.rb
scope '/projects/:project_id' do
  resources :test_suites
  resources :test_cases do
    member do
      post :delete_test_case_step
      get :move
    end
  end
  resources :test_suite_test_cases
  resources :test_plans do
    member do
      get :add_test_case
    end
  end
  resources :test_executions
  resources :test_execution_issues
end

get '/projects/:project_id/test', :to => 'testmine#index', as: 'testmine_index'
get '/projects/:project_id/test/test_execution/:test_execution_id', :to => 'testmine#test_execution', as: 'testmine_test_execution'
get '/projects/:project_id/test/test_plan/:test_plan_id', :to => 'testmine#test_plan', as: 'testmine_test_plan'
get '/projects/:project_id/test/edit_test_plan/:test_plan_id', :to => 'testmine#edit_test_plan', as: 'testmine_edit_test_plan'

# get '/projects/:project_id/test_suites', :to => 'test_suites#index', as: 'test_suites'
# get '/projects/:project_id/test_suites/new', :to => 'test_suites#new', as: 'new_test_suite'
# post '/projects/:project_id/test_suites', :to => 'test_suites#create', as: 'test_suites'

# get '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#index', as: 'test_cases'
# get '/projects/:project_id/test_suites/:test_suite_id/test_cases/new', :to => 'test_cases#new', as: 'new_test_case'
# post '/projects/:project_id/test_suites/:test_suite_id/test_cases', :to => 'test_cases#create', as: 'test_cases'

app/models/test_plan.rb
class TestPlan < ActiveRecord::Base
  unloadable

  attr_accessible :title, :summary, :start_on, :finish_on
  attr_accessible :created_by_user_id, :executed_by_user_id, :project_id, :test_plan_status_id

  belongs_to :project

  belongs_to :test_plan_status
  belongs_to :executed_by, class_name: 'User', foreign_key: :executed_by_user_id
  belongs_to :created_by, class_name: 'User', foreign_key: :created_by_user_id

  has_many :test_executions
  has_many :test_cases, through: :test_executions

  before_create :set_created_by

  def finished?
    if self.test_plan_status.nil?
      false
    else
      self.test_plan_status.name.to_s.in?(["Complete", "Incomplete", "Canceled"])
    end
  end

  def modifiable?
    !finished?
  end

  def executable?
    !finished?
  end

  private

  def set_created_by
    self.created_by = User.current
  end
end

app/controllers/test_plans_controller.rb
class TestPlansController < ApplicationController
  unloadable

  before_filter :find_project
  before_filter :authorize#, except: [ :add_test_case ]

  after_filter :set_finish_on, on: [ :update ]

  def show
    @title = "View Test Plan"
    @disabled_form = true
    edit
  end

  def new
    @test_plan = TestPlan.new(project_id: @project.id)

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :new, layout: use_layout
  end

  def edit
    @test_plan = TestPlan.find(params[:id])

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :edit, layout: use_layout
  end

  def create
    @test_plan = TestPlan.new(params[:test_plan])
    @test_plan.project_id = @project.try(:id) || params[:test_plan][:project_id]

    if @test_plan.save
      render 'create.js'
    end
  end

  def update
    @test_plan = TestPlan.find(params[:id])

    if @test_plan.update_attributes(params[:test_plan])
      render 'update.js'
    end
  end

  def add_test_case
    @test_plan = TestPlan.find(params[:id])
    @test_execution = TestExecution.new
    @test_execution.test_plan_id = @test_plan.id

    @existing_test_cases = @test_plan.test_cases.pluck(:id).uniq

    puts @existing_test_cases.inspect

    if params[:use_layout] == "yes"
      use_layout = true
    else
      use_layout = false
    end

    render :add_test_case, layout: use_layout
  end

  def destroy
    @test_plan = TestPlan.find(params[:id])

    if @test_plan.destroy
      TestExecution.where(test_plan_id: @test_plan.id).destroy_all
      render 'destroy.js'
    end
  end

  private
  def find_project
    identifier = params[:project_id]
    identifier ||= params[:test_plan][:project_id] if params[:test_plan]

    @project = Project.find(identifier)
  end

  def set_finish_on
    if @test_plan && @test_plan.finished?
      @test_plan.finish_on = DateTime.now
      @test_plan.save
    end
  end
end

app/views/test_plans/_form.html.erb
<h3>
  <% if @title.present? %>
    <%= @title %>
  <% else %>
    <% if @test_plan.persisted? %>
      Edit Test Plan
    <% else %>
      New Test Plan
    <% end %>
  <% end %>
</h3>
<%
  options = { remote: true }
  if @test_plan.persisted?
    options[:url] = test_plan_path(@project, @test_plan)
  else
    options[:url] = test_plans_path(@project)
  end
%>
<%= labelled_form_for @test_plan, options do |f| %>
  <p>
    <%= f.text_field :title, label: 'Title' %>
  </p>
  <p>
    <%= f.text_area :summary, label: 'Summary', rows: 5 %>
  </p>
  <div class="two-columns">
    <div class="column">
      <p>
        <%= f.date_select :start_on, label: 'Date Start', order: [ :day, :month, :year ] %>
      </p>
      <p>
        <label for="test_plan_start_on">Time Start</label>
        <%= f.time_select :start_on, label: false, ignore_date: true %>
      </p>
    </div>
    <div class="column">
      <p>
        <%= f.date_select :finish_on, label: 'Date Finish', order: [ :day, :month, :year ] %>
      </p>
      <p>
        <label for="test_plan_finish_on">Time Finish</label>
        <%= f.time_select :finish_on, label: false, ignore_date: true %>
      </p>
    </div>
  </div>
  <p>
    <%= f.select :created_by_user_id, options_from_collection_for_select(User.all, :id, :name, @test_plan.created_by_user_id || User.current.id), label: 'Create by' %>
  </p>
  <p>
    <%= f.select :executed_by_user_id, options_from_collection_for_select(User.all, :id, :name, @test_plan.executed_by_user_id), label: 'Execution by', include_blank: true %>
  </p>
  <%= f.hidden_field :project_id %>
  <%= submit_tag 'Save', disabled: @disabled_form %>
  <input type="reset" value="Cancelar" class="close-modal" />
<% end %>

app/views/test_plans/_index.html.erb
<a href="<%= new_test_plan_path(@project) %>" class="show-new-test-plan"><small>New test plan</small></a>

<ul id="project_test_plans">
  <%= render partial: 'test_plans/show', collection: @project.test_plans, as: :test_plan %>
</ul>

<script type="text/html" id="new-test-plan-modal-content">
  <%= render 'test_plans/form' %>
</script>

<script type="text/html" id="show-test-plan-modal-content">
</script>

<script type="text/html" id="edit-test-plan-modal-content">
</script>

<script type="text/html" id="add-test-case-modal-content">
</script>

app/views/test_plans/_show.html.erb
<li id="test_plan_<%= test_plan.id %>">
  <h4 title="<%= test_plan.summary %>">
    <span>
      <%= test_plan.title %> <a href="#" class="show_menu">(<%= test_plan.test_cases.count %>)</a>
    </span>
    <ul class="menu">
      <li>
        <a href="<%= test_plan_path(@project, test_plan) %>" class="show-test-plan">
          View test plan
        </a>
      </li>
      <li>
        <a href="<%= edit_test_plan_path(@project, test_plan) %>" class="show-edit-test-plan">
          Edit test plan
        </a>
      </li>
      <li>
        <%= link_to "Delete test plan", test_plan_path(@project, test_plan), method: :delete, remote: true, confirm: "Are you sure you want to delete \"#{test_plan.title}\" Test Plan?" %>
      </li>
      <li style="border-top: solid 1px #999">
        <a href="<%= add_test_case_test_plan_path(@project, test_plan) %>" class="show-add-test-case">
          Add test case
        </a>
      </li>
    </ul>
  </h4>
  <ul class="test_plan_test_cases">
    <%= render partial: 'test_cases/show', collection: test_plan.test_cases, as: :test_case, locals: { test_plan_id: test_plan.id } %>
  </ul>
</li>

app/views/test_plans/add_test_case.html.erb
<h3>Add Test Case</h3>

<%= labelled_form_for @test_execution, remote: true do |f| %>
  <p>
    <%
      if @existing_test_cases.empty?
        condition = :test_cases
      else
        condition = "test_cases.where('test_cases.id NOT IN (?)', #{@existing_test_cases})"
      end
    %>
    <%= f.select :test_case_id, option_groups_from_collection_for_select(@project.test_suites, condition, :name, :id, :title, @test_execution.test_case_id), { label: 'Select Test Case' }, { size: 3 } %>
  </p>
  <%= f.hidden_field :test_plan_id %>
  <%= submit_tag 'Save' %>
  <input type="reset" value="Cancelar" class="close-modal" />
<% end %>

app/views/test_plans/create.js.erb
$("#project_test_plans").append("<%= escape_javascript(render(partial: 'test_plans/show', locals: { test_plan: @test_plan })) %>");

if (window.currentModal) {
  window.currentModal.close();
}

app/views/test_plans/destroy.js.erb
$('#test_plan_<%= @test_plan.id %>').remove();

if (window.currentModal) {
  window.currentModal.close();
}

app/views/test_plans/edit.html.erb
<%= render 'test_plans/form' %>

app/views/test_plans/new.html.erb
<%= render 'test_plans/form' %>

app/views/test_plans/update.js.erb
$('#test_plan_<%= @test_plan.id %>').find('h4 span').html('<%= @test_plan.title %> <a href="#" class="show_menu">(<%= @test_plan.test_cases.count %>)</a>');

if (window.currentModal) {
  window.currentModal.close();
}